version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ancalagon_index: "${ANCALAGON_INDEX}"
        ancalagon_token: "${ANCALAGON_TOKEN}"
    environment:
      - GOVEE_PORT=3000
      - GOVEE_API_KEY=${GOVEE_API_KEY}
      - GOVEE_REDIS_URI=redis://redis:6379
    depends_on:
      - redis
    ports:
      - "3000:3000"

  redis:
    image: redis:alpine
    expose:
      - "6379"
